#ifndef QNATIVEWEBVIEW_GLOBAL_H
#define QNATIVEWEBVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNATIVEWEBVIEW_LIBRARY)
#  define QNATIVEWEBVIEW_EXPORT Q_DECL_EXPORT
#else
#  define QNATIVEWEBVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // QNATIVEWEBVIEW_GLOBAL_H
